export {default as Hero}   from './Hero'
export {default as About}   from './About'
export {default as Services}   from './Services'
export {default as Portfolio}   from './Portfolio'
export {default as Clients}   from './Clients'
export {default as ContactUs}   from './ContactUs'